# Generated by Django 3.2.12 on 2022-04-23 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_email_handling'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The moment when the item was created.')),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True, help_text='The last moment when the item was modified. A value in year 1750 indicates the value is unknown')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique message identifier.')),
                ('recipient', models.EmailField(help_text='The email address to which the delivery failed.', max_length=254)),
                ('status', models.SmallIntegerField(choices=[(0, 'Waiting for a delivery signal to enqueue.'), (1, 'Awaiting processing in queue after a backoff event.'), (2, 'Awaiting processing in queue due to a delivery event.'), (3, 'Item is currently being processed.'), (4, 'Item processed successfully.')], default=0, help_text='The enqueue failed message status.')),
                ('next_retry_date', models.DateTimeField(blank=True, help_text='The scheduled datetime to retry sending the message.', null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='failedemail',
            index=models.Index(fields=['recipient'], name='users_faile_recipie_c03e8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='failedemail',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 1)), fields=('recipient',), name='unique_failed_enqueued'),
        ),
    ]
